#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mastofessb"
name = "Masto-FE (ðŸ¦¥ flavour)"
description.en = "Mastodon-like interface for GoToSocial, based on IceShrimp's Masto-FE Standalone"
description.fr = "Interface Ã  la Mastodon pour GoToSocial, basÃ© sur Masto-FE Standalone d'IceShrimp"

version = "2025.10.12~ynh3"

maintainers = ["trendless"]

[upstream]
license = "AGPL-3.0"
demo = "https://masto-fe.superseriousbusiness.org/"
code = "https://codeberg.org/superseriousbusiness/masto-fe-standalone"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "3G"
ram.build = "2G"
ram.runtime = "300M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://codeberg.org/superseriousbusiness/masto-fe-standalone/archive/1ff70886a12e05cdc2f0789e78dcdabccaef6d18.tar.gz"
        sha256 = "72dc35b713204e39aeab8f06c480123643a8c214c5fc074d3b3477abd786516a"

        autoupdate.strategy = "latest_forgejo_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = ["yarn"]

    [resources.nodejs]
    version = "20"
